<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>471e97d8-491e-4861-b17d-bf9fa32739f0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ResourcePlatform.Domain\ResourcePlatform.Domain.csproj" />
    <ProjectReference Include="..\ResourcePlatform.Infrastructure\ResourcePlatform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
