// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourcePlatform.Infrastructure;

#nullable disable

namespace ResourcePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831213949_AddPermissions")]
    partial class AddPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.OrganizationMembership", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c0b81b0-84c5-b25b-8699-6ee51997f255"),
                            Name = "Location.Read"
                        },
                        new
                        {
                            Id = new Guid("049b4483-ce6a-35c1-c766-2601f8552cef"),
                            Name = "Location.Create"
                        },
                        new
                        {
                            Id = new Guid("455c5b15-5934-c2b1-d7c1-cd0daafbede1"),
                            Name = "Location.Update"
                        },
                        new
                        {
                            Id = new Guid("6f17ae43-ba84-9a2a-2c16-10223715ff7b"),
                            Name = "Location.Delete"
                        },
                        new
                        {
                            Id = new Guid("f911858b-88cd-7c16-f923-3c0a8c7b0260"),
                            Name = "ResourceType.Read"
                        },
                        new
                        {
                            Id = new Guid("be94b080-b979-2550-66ac-8cb84826e55a"),
                            Name = "ResourceType.Create"
                        },
                        new
                        {
                            Id = new Guid("1e71a3fa-0d38-b71a-18a6-0ca32ed8de0b"),
                            Name = "ResourceType.Update"
                        },
                        new
                        {
                            Id = new Guid("1ae7500c-7a1c-58c5-1fcf-920141b79c57"),
                            Name = "ResourceType.Delete"
                        },
                        new
                        {
                            Id = new Guid("556ec1b1-7aeb-7091-51b2-3f00f194ae80"),
                            Name = "Resource.Read"
                        },
                        new
                        {
                            Id = new Guid("d125ccf7-474b-e193-0883-221b06dea83b"),
                            Name = "Resource.Create"
                        },
                        new
                        {
                            Id = new Guid("c8ace02b-0da5-71ee-e024-22cd3e485a9c"),
                            Name = "Resource.Update"
                        },
                        new
                        {
                            Id = new Guid("7347c061-93f9-2981-b53d-d999ce39d021"),
                            Name = "Resource.Delete"
                        },
                        new
                        {
                            Id = new Guid("53a9485b-0b9a-888c-8f80-73ec7b8d4c84"),
                            Name = "Reservation.Read"
                        },
                        new
                        {
                            Id = new Guid("3682e3d3-4ff6-8c0d-72ab-ba20bc58e31d"),
                            Name = "Reservation.Create"
                        },
                        new
                        {
                            Id = new Guid("79e23999-58c4-8219-234b-a6a3a9172e92"),
                            Name = "Reservation.CancelOwn"
                        },
                        new
                        {
                            Id = new Guid("b5dfd67b-408e-aa3b-0c71-d79be7fab61f"),
                            Name = "Reservation.CancelAny"
                        },
                        new
                        {
                            Id = new Guid("e5d436e7-73e7-09ca-d02b-fb337d790ad9"),
                            Name = "Reservation.Approve"
                        },
                        new
                        {
                            Id = new Guid("f38228da-566d-1152-2852-5a0a1a57368e"),
                            Name = "Member.Read"
                        },
                        new
                        {
                            Id = new Guid("be48da10-f3dc-48e1-2112-a8eb0002f8ba"),
                            Name = "Member.Invite"
                        },
                        new
                        {
                            Id = new Guid("fe0751d0-fdf4-6e60-5dda-b45f5e4967f9"),
                            Name = "Member.Remove"
                        },
                        new
                        {
                            Id = new Guid("95185dfc-4aea-c4d8-66c5-77235e0c3075"),
                            Name = "Member.AssignRole"
                        },
                        new
                        {
                            Id = new Guid("ff95a46b-d616-d6a2-ddba-21506fc963f2"),
                            Name = "Organization.Update"
                        },
                        new
                        {
                            Id = new Guid("4091df6a-0088-e339-8960-a9d2a5910c99"),
                            Name = "Organization.Delete"
                        },
                        new
                        {
                            Id = new Guid("ed4f3f7f-eb00-1e61-003c-d0cb353bb39d"),
                            Name = "Audit.Read"
                        });
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ResourceId", "StartUtc", "EndUtc");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetTag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsReservable")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<Guid>("ResourceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("OrganizationId", "LocationId");

                    b.HasIndex("OrganizationId", "ResourceTypeId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ResourceTypes");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasFilter("[OrganizationId] IS NOT NULL");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            IsSystemRole = true,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsSystemRole = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            IsSystemRole = true,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            IsSystemRole = true,
                            Name = "Member"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            IsSystemRole = true,
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("ResourcePlatform.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("8c0b81b0-84c5-b25b-8699-6ee51997f255")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("049b4483-ce6a-35c1-c766-2601f8552cef")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("455c5b15-5934-c2b1-d7c1-cd0daafbede1")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("6f17ae43-ba84-9a2a-2c16-10223715ff7b")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("f911858b-88cd-7c16-f923-3c0a8c7b0260")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("be94b080-b979-2550-66ac-8cb84826e55a")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("1e71a3fa-0d38-b71a-18a6-0ca32ed8de0b")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("1ae7500c-7a1c-58c5-1fcf-920141b79c57")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("556ec1b1-7aeb-7091-51b2-3f00f194ae80")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("d125ccf7-474b-e193-0883-221b06dea83b")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("c8ace02b-0da5-71ee-e024-22cd3e485a9c")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("7347c061-93f9-2981-b53d-d999ce39d021")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("53a9485b-0b9a-888c-8f80-73ec7b8d4c84")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("3682e3d3-4ff6-8c0d-72ab-ba20bc58e31d")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("79e23999-58c4-8219-234b-a6a3a9172e92")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b5dfd67b-408e-aa3b-0c71-d79be7fab61f")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("e5d436e7-73e7-09ca-d02b-fb337d790ad9")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("f38228da-566d-1152-2852-5a0a1a57368e")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("be48da10-f3dc-48e1-2112-a8eb0002f8ba")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("fe0751d0-fdf4-6e60-5dda-b45f5e4967f9")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("95185dfc-4aea-c4d8-66c5-77235e0c3075")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("ff95a46b-d616-d6a2-ddba-21506fc963f2")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("4091df6a-0088-e339-8960-a9d2a5910c99")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("ed4f3f7f-eb00-1e61-003c-d0cb353bb39d")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("8c0b81b0-84c5-b25b-8699-6ee51997f255")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("049b4483-ce6a-35c1-c766-2601f8552cef")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("455c5b15-5934-c2b1-d7c1-cd0daafbede1")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("6f17ae43-ba84-9a2a-2c16-10223715ff7b")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("f911858b-88cd-7c16-f923-3c0a8c7b0260")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("be94b080-b979-2550-66ac-8cb84826e55a")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("1e71a3fa-0d38-b71a-18a6-0ca32ed8de0b")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("1ae7500c-7a1c-58c5-1fcf-920141b79c57")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("556ec1b1-7aeb-7091-51b2-3f00f194ae80")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("d125ccf7-474b-e193-0883-221b06dea83b")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("c8ace02b-0da5-71ee-e024-22cd3e485a9c")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("7347c061-93f9-2981-b53d-d999ce39d021")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("53a9485b-0b9a-888c-8f80-73ec7b8d4c84")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("3682e3d3-4ff6-8c0d-72ab-ba20bc58e31d")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("79e23999-58c4-8219-234b-a6a3a9172e92")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b5dfd67b-408e-aa3b-0c71-d79be7fab61f")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("e5d436e7-73e7-09ca-d02b-fb337d790ad9")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("f38228da-566d-1152-2852-5a0a1a57368e")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("be48da10-f3dc-48e1-2112-a8eb0002f8ba")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("fe0751d0-fdf4-6e60-5dda-b45f5e4967f9")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("95185dfc-4aea-c4d8-66c5-77235e0c3075")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("ed4f3f7f-eb00-1e61-003c-d0cb353bb39d")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("8c0b81b0-84c5-b25b-8699-6ee51997f255")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("f911858b-88cd-7c16-f923-3c0a8c7b0260")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("556ec1b1-7aeb-7091-51b2-3f00f194ae80")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("d125ccf7-474b-e193-0883-221b06dea83b")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("c8ace02b-0da5-71ee-e024-22cd3e485a9c")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("53a9485b-0b9a-888c-8f80-73ec7b8d4c84")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("3682e3d3-4ff6-8c0d-72ab-ba20bc58e31d")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("79e23999-58c4-8219-234b-a6a3a9172e92")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("b5dfd67b-408e-aa3b-0c71-d79be7fab61f")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("e5d436e7-73e7-09ca-d02b-fb337d790ad9")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("f38228da-566d-1152-2852-5a0a1a57368e")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("8c0b81b0-84c5-b25b-8699-6ee51997f255")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("f911858b-88cd-7c16-f923-3c0a8c7b0260")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("556ec1b1-7aeb-7091-51b2-3f00f194ae80")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("53a9485b-0b9a-888c-8f80-73ec7b8d4c84")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("3682e3d3-4ff6-8c0d-72ab-ba20bc58e31d")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("79e23999-58c4-8219-234b-a6a3a9172e92")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("f38228da-566d-1152-2852-5a0a1a57368e")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("8c0b81b0-84c5-b25b-8699-6ee51997f255")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("f911858b-88cd-7c16-f923-3c0a8c7b0260")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("556ec1b1-7aeb-7091-51b2-3f00f194ae80")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("53a9485b-0b9a-888c-8f80-73ec7b8d4c84")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("f38228da-566d-1152-2852-5a0a1a57368e")
                        });
                });

            modelBuilder.Entity("ResourcePlatform.Infrastructure.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ResourcePlatform.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ResourcePlatform.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ResourcePlatform.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Department", b =>
                {
                    b.HasOne("ResourcePlatform.Domain.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Location", b =>
                {
                    b.HasOne("ResourcePlatform.Domain.Organization", "Organization")
                        .WithMany("Locations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.OrganizationMembership", b =>
                {
                    b.HasOne("ResourcePlatform.Domain.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourcePlatform.Domain.Role", "Role")
                        .WithMany("Memberships")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Reservation", b =>
                {
                    b.HasOne("ResourcePlatform.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourcePlatform.Domain.Resource", "Resource")
                        .WithMany("Reservations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Resource", b =>
                {
                    b.HasOne("ResourcePlatform.Domain.Department", "Department")
                        .WithMany("Resources")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResourcePlatform.Domain.Location", "Location")
                        .WithMany("Resources")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResourcePlatform.Domain.Organization", "Organization")
                        .WithMany("Resources")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourcePlatform.Domain.ResourceType", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Location");

                    b.Navigation("Organization");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.ResourceType", b =>
                {
                    b.HasOne("ResourcePlatform.Domain.Organization", "Organization")
                        .WithMany("ResourceTypes")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Role", b =>
                {
                    b.HasOne("ResourcePlatform.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ResourcePlatform.Domain.RolePermission", b =>
                {
                    b.HasOne("ResourcePlatform.Domain.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourcePlatform.Domain.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Department", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Location", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Organization", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Locations");

                    b.Navigation("Memberships");

                    b.Navigation("ResourceTypes");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Resource", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.ResourceType", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ResourcePlatform.Domain.Role", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
